# Generated by Django 2.2.28 on 2024-03-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0002_auto_20240308_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='No description provided.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True),
            preserve_default=False,
        ),
    ]
