# Generated by Django 2.2.28 on 2024-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0002_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='media/profile_images/default.jpg', upload_to='profile_images'),
        ),
    ]
