# Generated by Django 2.2.28 on 2024-03-18 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('renova', '0002_auto_20240308_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='activities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='announcements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(blank=True, upload_to='group_icons'),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Unnamed Group', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='log',
            name='sleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='total_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='water',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='activities',
            field=models.ManyToManyField(to='renova.Activity'),
        ),
    ]
