# Generated by Django 2.2.28 on 2024-03-21 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0003_auto_20240321_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='activities',
        ),
        migrations.AddField(
            model_name='activity',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renova.Log'),
        ),
    ]
