# Generated by Django 2.2.28 on 2024-03-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0003_auto_20240318_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='10k-runners', unique=True),
            preserve_default=False,
        ),
    ]
