# Generated by Django 2.2.28 on 2024-03-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0003_auto_20240321_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_calories',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_sleep',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_water',
            field=models.IntegerField(default=2500),
        ),
    ]
