# Generated by Django 2.2.28 on 2024-03-21 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0004_auto_20240321_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='renova.Log'),
        ),
    ]
