# Generated by Django 2.2.28 on 2024-03-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0005_auto_20240321_2338'),
        ('renova', '0004_auto_20240322_0055'),
    ]

    operations = [
    ]
