# Generated by Django 2.2.28 on 2024-03-18 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('renova', '0005_auto_20240318_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
