# Generated by Django 2.2.28 on 2024-03-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0006_merge_20240322_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', upload_to='profile_images'),
        ),
    ]
