# Generated by Django 2.2.28 on 2024-03-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renova', '0006_group_members'),
        ('renova', '0003_auto_20240317_0130'),
    ]

    operations = [
    ]
